### ISSUE TITLE
missing files using Get-Ttd.ps1

### ISSUE THREAD

**Issue by binjo** [microsoft/WinDbg-Samples#114]
The exclude file list in [Get-Ttd.ps1](https://github.com/microsoft/WinDbg-Samples/blob/e6c98d3cb4f16dfeef7f8330ed9e7268ad3b878f/TTD/LiveRecorderApiSample/Get-Ttd.ps1#L48) is incomplete, and the sub directories removed incorrectly(e.x **x86** under **x64**), these results the extracted TTD files incomplete.

With modification like following, should be good for downloading purpose:
```PowerShell
$ttdRecorderFiles = @(
    "*.exe",
    "*.dll",
    "*.sys"
)
```

and
```PowerShell
    # Remove empty subdirectories only
    Get-ChildItem -Directory $msixOutDir |  Where-Object { $($_ | Get-ChildItem -Force | Select-Object -First 1).Count -eq 0 } |
       Remove-Item -Recurse -Force
```

I understand the tool is not official installer, just for the record.

Thanks.

**Comment by KenSykes** [comment]
All the files needed for doing live recording, per the API sample, are downloaded with this script. You are right that there are more recorder files.  If you want a way to get the full set of TTD recording functionality without an installer you can use the script mentioned here:

https://learn.microsoft.com/en-us/windows-hardware/drivers/debuggercmds/time-travel-debugging-ttd-exe-command-line-util#how-to-download-and-install-the-ttdexe-command-line-utility-offline-method

This produces all of the files you are looking for:

`ls -Recurse ttd_offline

    Directory: C:\temp\ttd_offline

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          11/12/2024  1:56 PM                x86
-a---           9/11/2024 12:09 AM          79240 ProcLaunchMon.sys
-a---           9/11/2024 12:09 AM         112568 TTD.exe
-a---           9/11/2024 12:09 AM         309280 TTDInject.exe
-a---           9/11/2024 12:09 AM          59424 TTDLiveRecorder.dll
-a---           9/11/2024 12:09 AM          55352 TTDLoader.dll
-a---           9/11/2024 12:09 AM         903224 TTDRecord.dll
-a---           9/11/2024 12:09 AM        1300536 TTDRecordCPU.dll
-a---           9/11/2024 12:09 AM          71736 TTDRecordUI.dll
-a---           9/11/2024 12:09 AM        1230904 TTDReplay.dll
-a---           9/11/2024 12:09 AM        2766904 TTDReplayCPU.dll

    Directory: C:\temp\ttd_offline\x86

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           9/11/2024 12:09 AM         247840 TTDInject.exe
-a---           9/11/2024 12:09 AM          59424 TTDLiveRecorder.dll
-a---           9/11/2024 12:09 AM          43040 TTDLoader.dll
-a---           9/11/2024 12:09 AM        1185824 TTDRecordCPU.dll
`
