### ISSUE TITLE
Error: Unknown exception 

### ISSUE THREAD

**Issue by A-MMartin** [microsoft/WinDbg-Samples#13]
Hi,
I have imported successfully the script CodeFlow.js via .scriptload but I'm not able to get the control flow from certain address using "dx Debugger.Utility.Code.TraceDataFlow(address)" or its alias !dflow address. All I get are errors like:

**Error: Unknown exception [at CodeFlow (line 734 col 9)]**

Not sure if the address format is correct (0x00414122, 00414122) or the error is caused by another problem. I have tried with addresses and symbols from different processes (x86 and 64) with no luck. Could you please set any example along with the output. I haven't found anything.

I'm using WinDBG Preview (1.0.1910.03003) from Windows 10.
Thank you

**Comment by udonsi-kc** [comment]
I also experience this exception on WinDBG Preview (1.0.2001.02001) Windows 10

**Comment by TimMisiak** [comment]
Unfortunately, I didn't see this issue when this was opened. If this is still an issue, please feel free to reopen with instructions on how to reproduce and I will take a look.
