### ISSUE TITLE
JsProvider.d.ts issue

### ISSUE THREAD

**Issue by ImanHosseini** [microsoft/WinDbg-Samples#29]
I can see that "host.namespace.Debugger.Utility.*" functionality _does_ work in WinDbg, _but_ it is not included in the 'JsProvider.d.ts' that came with my Windows Kit (it has most of the stuff, but does not have the [Utility] part, why? And why can't we just get the "JsProvider.d.ts" here in this repo? 
[I tried the Scripting ribbon, it also does not suggest "Utility" after "host.namespace.Debugger." this is probably a bug?]

**Comment by TimMisiak** [comment]
The typescript definition is meant to be a helper, but it can't be completely exhaustive since the data model namespace is dynamic. I will see if there are more static entries we can add to be helpful here. Thanks for the feedback!
