### ISSUE TITLE
Redistribution of "ext.dll"

### ISSUE THREAD

**Issue by ibebbs** [microsoft/WinDbg-Samples#52]
I've recently been looking into using [Microsoft.Debugging.Platform.DbgX](https://www.nuget.org/packages/Microsoft.Debugging.Platform.DbgX) to perform remote analysis of minidump files. It's working great but I need to include "ext.dll" in order to use the "!analyze -v" command (which conveniently gives us all the information we need).

Are there any plans to include this in the 'Microsoft.Debugging.Platform.DbgX' package? If not, is "ext.dll" licensed for redistribution? This concern is currently blocking the adoption of DgbX.

**Comment by TimMisiak** [comment]
I talked with the !analyze team about this today. This is something they would like to do, but they don't have a specific timeline for when they will be able to publish and license ext.dll as a redistributable.
