### ISSUE TITLE
Are there any ways to troubleshoot gallery loading?

### ISSUE THREAD

**Issue by AlanAtWork** [microsoft/WinDbg-Samples#59]
I am including a BinaryComponent in my manifest, based on the manifest.1.xml that ships with the SDK. I am able to .load and use the extension fine on my own but the ExtensionPackage that contains it is not being loaded. I can see from procmon that it is not attempting to open the file. I've looked at the Logs window but I don't see anything relevant. Is there any other logging I can enable/find that might help me discover the problem?

**Comment by AlanAtWork** [comment]
I think I've found the problem after quite a bit of trial and error: It seems that the Name property on BinaryComponent must match the module name minus the path in the File node. Kind of a gotcha, some sort of diagnostic info would be helpful.

**Comment by TedyHH** [comment]
Around mid May 2022 we added more logging to help diagnose extension gallery issues and they are displayed via the logs view on WinDbgX (or WinDbgPreview in the MS store). You can search for ExtensionGallery entries there. To display the logs view you can just go to menu View->Logs.

**Comment by AlanAtWork** [comment]
Interesting. I did check out the log through View->Logs but I don't recall seeing anything germane to my issue, at least.
