### ISSUE TITLE
Error loading CodeFlow extension

### ISSUE THREAD

**Issue by john-soklaski** [microsoft/WinDbg-Samples#9]
I'm trying to load the CodeFlow.js extension using `.scriptload`, and I get this error: `Error (0x80004005): Cannot modify debugger object model for 'functionAlias (dflow)'`.

I am able to successfully load the ImageInfo.js extension in the same manner though.

**Comment by john-soklaski** [comment]
If I remove both of the `functionAlias` it will load successfully.
```
new host.functionAlias(__traceDataFlow, "dflow"),
new host.functionAlias(__disassembleCode, "dis")
```

**Comment by aluhrs13** [comment]
Thanks John, we'll take a look at this. Can you share what debugger version you're using?

**Comment by lzybkr** [comment]
It seems like this is no longer an issue, so I'm closing the issue. Feel free to open a new issue if you see it again.

**Comment by kiwids0220** [comment]
I am having the same issue here Error (0x80004005): Cannot modify debugger object model for 'functionAlias (dflow)'

**Comment by kiwids0220** [comment]
> [@kiwids0220](https://github.com/kiwids0220) - please open a new issue and provide repro steps and the debugger version you are testing.

Thanks for the reply! I figured the issue was with KD, seems like the script only works under user mode debugging.
